auth_endpoint = "https://www.strava.com/oauth/authorize"
activites_endpoint = "https://www.strava.com/api/v3/athlete/activities"
token_endpoint = "https://www.strava.com/oauth/token"
# local_endpoint = "http://localhost:8501/"
local_endpoint = "https://runningapp-4hywrzgxiw5gbicenbi9nh.streamlit.app/"
